# Site settings
title: Qingrong Chen
email: chenqr1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Research Engineer at Bytedance, working on large lanague model systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chenqingrong.github.io" # the base hostname & protocol for your site
production_url: "https://www.chenqingrong.githhub.io"
github_username: chenqingrong
permalink: /blog/:year/:month/:title.html

twitter:
  username: Qingrong8

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
