# Site settings
title: Leo Chen
email: chenqr1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Member of Technical Staff at OpenAI, working on large lanague model systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.leochen-ai.github.io" # the base hostname & protocol for your site
production_url: "https://www.leochen-ai.githhub.io"
github_username: leochen-ai
permalink: /blog/:year/:month/:title.html

twitter:
  username: Qingrong8

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
